$(function(){
    $(".userindex").on('click',function(){
        $(location).attr('href','userIndex.html');
    })
    $(".allgame").on('click',function(){
        $(location).attr('href','非遗查询.html');
    })
    $(".myinfo").on('click',function(){
        $(location).attr('href','我的信息.html');
    })
    $(".aboutme").on('click',function(){
        $(location).attr('href','userIndex.html');
    })
})